# Generated by Django 2.0.6 on 2018-07-21 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(null=True)),
            ],
            options={
                'db_table': 'developer',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('release_year', models.PositiveSmallIntegerField(null=True)),
                ('release_month', models.PositiveSmallIntegerField(null=True)),
                ('release_day', models.PositiveSmallIntegerField(null=True)),
                ('overview', models.TextField(null=True)),
                ('esrb_rating', models.CharField(choices=[('E', 'EVERYONE'), ('E10', 'EVERYONE 10+'), ('T', 'TEEN'), ('M', 'MATURE'), ('A', 'ADULTS'), ('RP', 'RATING PENDING')], max_length=16, null=True)),
                ('players', models.CharField(max_length=100, null=True)),
                ('coop', models.NullBooleanField()),
                ('rating', models.FloatField(null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('notes', models.CharField(max_length=100, null=True)),
                ('finished', models.NullBooleanField()),
                ('original', models.NullBooleanField()),
                ('playtime', models.PositiveIntegerField(null=True)),
                ('youtube_url', models.URLField(null=True)),
                ('logo_url', models.URLField(null=True)),
                ('status', models.CharField(choices=[('NOT_SYNCHED', 'Not Synchronized'), ('SYNCHED', 'Synchronized')], editable=False, max_length=16, null=True)),
                ('store', models.CharField(choices=[('BLIZZARD', 'Blizzard'), ('GOG', 'GoG'), ('HUMBLE_BUNDLE', 'Humble Bundle'), ('ORIGIN', 'Origin'), ('PSN', 'PSN'), ('STEAM', 'Steam'), ('OTHER', 'Other')], max_length=32, null=True)),
                ('store_game_id', models.CharField(max_length=36, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('developer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='games.Developer')),
            ],
            options={
                'db_table': 'game',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'platform',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(null=True)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(db_table='game_genre', to='games.Genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(db_table='game_platform', to='games.Platform'),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='games.Publisher'),
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(db_table='game_tag', to='games.Tag'),
        ),
        migrations.AddField(
            model_name='game',
            name='user',
            field=models.ManyToManyField(db_table='user_game', to=settings.AUTH_USER_MODEL),
        ),
    ]
